[package]
name = "pi_spatialtree"
version = "0.3.0"
authors = ["yineng <dev@dev.com>"]
edition = "2018"

[dependencies]
ncollide2d = "0.33"
ncollide3d = "0.33"
nalgebra = "0.30"
num-traits = "0.2"
pi_slotmap="0.1"
pi_map = "0.1"
pi_null = "0.1"

[dev-dependencies]
pcg_rand = "0.12"
rand = "0.7"